# Generated by Django 5.2.4 on 2025-07-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Presentation', 'verbose_name_plural': 'Presentations'},
        ),
    ]
