# Generated by Django 5.2.4 on 2025-07-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_presentation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={},
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True, default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presentation',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='presentation_images/'),
        ),
    ]
