# Generated by Django 5.2.4 on 2025-07-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_presentation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.CharField(default="Ma'ruza mashg'uloti", max_length=255),
        ),
    ]
