# Generated by Django 6.0 on 2026-02-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_presentation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaholashMezoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fayl', models.FileField(upload_to='metodik/baholash/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='lectures/')),
                ('quiz_json', models.CharField(blank=True, help_text='Masalan: topic_01.json (tests papkasida turadi)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MashgulotIshlanmalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fayl', models.FileField(upload_to='metodik/mashgulot/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaslahatTavsiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fayl', models.FileField(upload_to='metodik/maslahat/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MeyoriyHujjat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tur', models.CharField(choices=[('qonun', 'Qonunlar'), ('qaror', 'Qarorlar'), ('farmon', 'Farmonlar'), ('buyruq', 'Buyruqlar'), ('nizom', 'Nizomlar'), ('boshqa', 'Boshqa hujjatlar')], default='boshqa', max_length=20)),
                ('fayl', models.FileField(upload_to='meyoriy_hujjatlar/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PedagogikTexnologiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fayl', models.FileField(upload_to='metodik/ped_tex/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
