# Generated by Django 6.0 on 2026-02-01 11:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_baholashmezoni_lecture_mashgulotishlanmalari_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['lecture_number', 'id']},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='pdf',
        ),
        migrations.AddField(
            model_name='lecture',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lecture',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.models.lecture_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='baholashmezoni',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=core.models.metodik_file_upload_to),
        ),
        migrations.AlterField(
            model_name='mashgulotishlanmalari',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=core.models.metodik_file_upload_to),
        ),
        migrations.AlterField(
            model_name='maslahattavsiyalar',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=core.models.metodik_file_upload_to),
        ),
        migrations.AlterField(
            model_name='meyoriyhujjat',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=core.models.meyoriy_file_upload_to),
        ),
        migrations.AlterField(
            model_name='pedagogiktexnologiya',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=core.models.metodik_file_upload_to),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file',
            field=models.FileField(max_length=500, upload_to=core.models.presentation_file_upload_to),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=core.models.presentation_image_upload_to),
        ),
    ]
