# Generated by Django 6.0 on 2026-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lecture_options_remove_lecture_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='quiz_json',
            field=models.CharField(blank=True, help_text='Masalan: lecture_01.json', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
