# Generated by Django 5.2.4 on 2025-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeyoriyHujjat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='meyoriy_hujjatlar/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
