# Generated by Django 5.2.4 on 2025-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedagogikTexnologiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='pedagogik_texnologiyalar/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
