# Generated by Django 5.2.4 on 2025-07-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_pedagogiktexnologiya'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaholashMezoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='baholash_mezonlari/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MashgulotIshlanmalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='mashgulot_ishlanmalari/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaslahatTavsiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='maslahat_tavsiyalar/')),
                ('yuklashlar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
