# Generated by Django 5.2.4 on 2025-07-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_baholashmezoni_mashgulotishlanmalari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meyoriyhujjat',
            name='tur',
            field=models.CharField(choices=[('qonun', 'Qonunlar'), ('qaror', 'Qarorlar'), ('farmon', 'Farmonlar'), ('metodik', "O'quv-metodik ta'minot")], default='qonun', max_length=20),
        ),
    ]
