# Generated by Django 5.2.4 on 2025-07-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('subject', models.CharField(max_length=255, verbose_name='Fan nomi')),
                ('lecture_number', models.CharField(max_length=50, verbose_name='Mashg‘ulot tartib raqami')),
                ('pdf_file', models.FileField(upload_to='lectures/', verbose_name='PDF fayl')),
                ('image', models.ImageField(upload_to='lectures/images/', verbose_name='Rasm')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Yuklab olish soni')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
