# Generated by Django 5.2.4 on 2025-07-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_presentation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={},
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='image',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
