# Generated by Django 5.2.4 on 2025-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_alter_presentation_options_remove_presentation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='description',
        ),
        migrations.AddField(
            model_name='presentation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='presentations/images/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
