# Generated by Django 5.2.4 on 2025-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_remove_presentation_description_presentation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
