# Generated by Django 5.2.4 on 2025-07-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_alter_presentation_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='lecture_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
