# Generated by Django 5.2.4 on 2025-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_presentation_lecture_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='practicals/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='practicals/images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
