# Generated by Django 5.2.4 on 2025-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_practical'),
    ]

    operations = [
        migrations.AddField(
            model_name='practical',
            name='lecture_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Mashg‘ulot raqami'),
        ),
    ]
