# Generated by Django 5.2.4 on 2025-07-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_practical_lecture_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lesson_number', models.PositiveIntegerField()),
                ('youtube_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='practical',
            name='file',
            field=models.FileField(max_length=255, upload_to='practicals/'),
        ),
    ]
