# Generated by Django 6.0 on 2026-02-01 11:13

import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_videolesson_alter_practical_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['lecture_number', 'id']},
        ),
        migrations.AlterModelOptions(
            name='practical',
            options={'ordering': ['lecture_number', '-upload_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['lecture_number', '-upload_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='videolesson',
            options={'ordering': ['lesson_number', 'id']},
        ),
        migrations.AlterField(
            model_name='baholashmezoni',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=docs.models.upload_baholash),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=docs.models.upload_lecture_image, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_number',
            field=models.PositiveIntegerField(verbose_name='Mashg‘ulot tartib raqami'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=docs.models.upload_lecture_pdf, verbose_name='PDF fayl'),
        ),
        migrations.AlterField(
            model_name='mashgulotishlanmalari',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=docs.models.upload_mashgulot),
        ),
        migrations.AlterField(
            model_name='maslahattavsiyalar',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=docs.models.upload_maslahat),
        ),
        migrations.AlterField(
            model_name='meyoriyhujjat',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=docs.models.upload_meyoriy),
        ),
        migrations.AlterField(
            model_name='pedagogiktexnologiya',
            name='fayl',
            field=models.FileField(max_length=500, upload_to=docs.models.upload_ped_tex),
        ),
        migrations.AlterField(
            model_name='practical',
            name='file',
            field=models.FileField(max_length=500, upload_to=docs.models.upload_practical_file),
        ),
        migrations.AlterField(
            model_name='practical',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=docs.models.upload_practical_image),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file',
            field=models.FileField(max_length=500, upload_to=docs.models.upload_presentation_file),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=docs.models.upload_presentation_image),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='lecture_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Mashg‘ulot raqami'),
        ),
    ]
