# Generated by Django 6.0 on 2026-02-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_alter_lecture_options_alter_practical_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='image',
        ),
        migrations.AddField(
            model_name='lecture',
            name='quiz_json',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
