# Generated by Django 6.0 on 2026-03-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0016_alter_lecture_options_remove_lecture_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={},
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file',
            field=models.FileField(upload_to='presentations/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='presentations/images/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='lecture_number',
            field=models.PositiveIntegerField(),
        ),
    ]
